import os
import platform
import subprocess
import datetime

# Utility for system reports
def get_sys_info():
    kernel = platform.release()
    distro = platform.system()
    user = os.getlogin()
    home = os.path.expanduser('~')
    try:
        uptime = subprocess.check_output(['uptime', '-p']).decode().strip()
    except:
        uptime = "Unknown"
    now = datetime.datetime.now().strftime("%d %B %Y, %H:%M:%S")
    return {
        "kernel": kernel,
        "distro": distro,
        "user": user,
        "home": home,
        "uptime": uptime,
        "date": now
    }

# Utility for package inspection
def check_pkg(pkg_name):
    try:
        subprocess.check_call(["dpkg", "-l", pkg_name], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        details = subprocess.check_output(f"dpkg -l {pkg_name} | grep '^ii'", shell=True).decode()
        version = details.split()[2]
        return version
    except:
        return None

# Utility for directory auditing
def get_dir_stats(path):
    if os.path.exists(path):
        try:
            stat_info = subprocess.check_output(["ls", "-ld", path]).decode().split()
            perms = f"{stat_info[0]} {stat_info[2]} {stat_info[3]}"
            size = subprocess.check_output(["du", "-sh", path], stderr=subprocess.DEVNULL).decode().split()[0]
            return perms, size
        except:
            return "Error", "N/A"
    return None, None

# Utility for log scanning
def search_logs(log_path, key):
    matches = []
    if os.path.exists(log_path):
        with open(log_path, 'r') as f:
            for line in f:
                if key.lower() in line.lower():
                    matches.append(line.strip())
    return matches

# Utility for generating content
def gen_manifesto(tool, word, project):
    user = os.getlogin()
    now = datetime.datetime.now().strftime("%d %B %Y")
    filename = f"manifesto_{user}.txt"
    data = f'Generated by {user} on {now}\nTool: {tool}\nFreedom: {word}\nBuild: {project}'
    with open(filename, 'w') as f:
        f.write(data)
    return filename
